version: '{build}'
image: 'Visual Studio 2017'
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
init:
- ps: $PSVersionTable
install:
- ps: |
    cinst powershell -n --no-progress
    cinst gitversion gitreleasemanager.portable codecov au --no-progress
    Install-Module Pester -Scope CurrentUser -Force -SkipPublisherCheck
    $uri = "https://raw.githubusercontent.com/PowerShell/DscResource.Tests/491688867dc53894b92ca53520a18d145deb7760/DscResource.CodeCoverage/CodeCovIo.psm1"
    Invoke-WebRequest -Uri $uri -OutFile $env:USERPROFILE\CodeCovIo.psm1
- ps: Get-Module Pester -ListAvailable | select -First 1 | % { $_.Version.ToString() }
build_script:
- ps: |
    .\build -BuildDocs
test_script:
- ps: |
    Import-Module $env:USERPROFILE\CodeCovIo.psm1
    if ($env:APPVEYOR_REPO_BRANCH -notmatch '[\/\-]') {
        powershell -Version 3.0 -Command "$PWD\test.ps1 -CodeCoverage; exit $LASTEXITCODE"
    } else {
        powershell -Version 3.0 -Command "$PWD\test.ps1 -CodeCoverage -Pester; exit $LASTEXITCODE"
    }
artifacts:
- path: '**\*.nupkg'
- path: '**\*.7z'
notifications:
- provider: GitHubPullRequest
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
on_success:
- ps: .\publish.ps1
- cmd: codecov -f coverage.json

cache:
- docs/input/docs/functions
- docs/tools->docs/build.ps1
