version: '{build}'
image: 'Visual Studio 2017'
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
init:
- ps: $PSVersionTable
install:
- ps: |
    cinst gitversion gitreleasemanager.portable codecov transifex-client --no-progress
    Install-Module Pester -Scope CurrentUser -Force -SkipPublisherCheck
    $uri = "https://raw.githubusercontent.com/PowerShell/DscResource.Tests/491688867dc53894b92ca53520a18d145deb7760/DscResource.CodeCoverage/CodeCovIo.psm1"
    Invoke-WebRequest -Uri $uri -OutFile $env:USERPROFILE\CodeCovIo.psm1
build_script:
- ps: |
    tx init --host="https://www.transifex.com" --token="$env:TRANSIFEX_TOKEN"
    .\build
test_script:
- ps: |
    Import-Module $env:USERPROFILE\CodeCovIo.psm1
    .\test -CodeCoverage -Pester
artifacts:
- path: '**\*.nupkg'
- path: '**\*.7z'
notifications:
- provider: GitHubPullRequest
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
on_finish:
- cmd: codecov -f coverage.json
