pull_request_rules:
  - name: automatic merge when CI passes and 1 review
    conditions:
      - "#approved-reviews-by>=1"
      - status-success=continuous-integration/appveyor/pr
      - status-success=WIP
      - status-success=codecov/patch
      - status-success=license/cla
      - base=develop
    actions:
      merge:
        strict: smart
        method: merge
      delete_head_branch: {}
