blank_issues_enabled: false
contact_links:
  - name: Gitter Chat channel
    url: https://gitter.im/WormieCorp/Wormies-AU-Helpers?utm_source=share-link&utm_medium=link&utm_campaign=share-link
    about: Please ask and answer questions here
